# Kernel Logger
$(LOGGER_OBJ): $(LOGGER_H) $(LOGGER_CPP) $(TERMINAL_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) -c $(LOGGER_CPP) -o $(LOGGER_OBJ)

# Kernel Assert
$(ASSERT_OBJ): $(ASSERT_CPP) $(ASSERT_H) $(LOGGER_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) $(INCLUDE_KERNEL_FOLDER) -c $(ASSERT_CPP) -o $(ASSERT_OBJ)

# Kenrel IDT
$(IDT_ENTRY_OBJ): $(IDT_ENTRY_CPP) $(IDT_ENTRY_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_KERNEL_FOLDER) -c $(IDT_ENTRY_CPP) -o $(IDT_ENTRY_OBJ)

# Kernel Timer
$(TIMER_OBJ): $(TIMER_CPP) $(TIMER_H) $(LOGGER_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_KERNEL_FOLDER) $(INCLUDE_UTILITIES_FOLDER) -c $(TIMER_CPP) -o $(TIMER_OBJ)

# Kernel Exceptions
$(EXCEPTIONS_OBJ): $(EXCEPTIONS_CPP) $(EXCEPTIONS_H) $(LOGGER_H) $(IDT_ENTRY_H) $(INTERRUPT_FRAME_H) $(PIC_H) $(TIMER_H) $(PIT_H) $(KEYBOARD_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_KERNEL_FOLDER) $(INCLUDE_UTILITIES_FOLDER) $(INCLUDE_DRIVERS_FOLDER) $(INCLUDE) -c $(EXCEPTIONS_CPP) -o $(EXCEPTIONS_OBJ)

# Kernel PIC
$(PIC_OBJ): $(PIC_CPP) $(PIC_H) $(IO_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) -c $(PIC_CPP) -o $(PIC_OBJ)

# Kernel PIT
$(PIT_OBJ): $(PIT_CPP) $(PIT_H) $(IO_H) $(LOGGER_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) -c $(PIT_CPP) -o $(PIT_OBJ)

# Memory E820
$(MEMORY_E820_OBJ): $(MEMORY_E820_CPP) $(MEMORY_E820_H)
	$(CC) $(COMPILE_FLAGS) -c $(MEMORY_E820_CPP) -o $(MEMORY_E820_OBJ)