$(KERNEL_OBJ): $(KERNEL_CPP)
	$(CC) $(COMPILE_FLAGS) $(KERNEL_CPP) -o $(KERNEL_OBJ)

$(KERNEL_ELF): $(KERNEL_OBJ)
	$(LD) -T $(KERNEL_LINKER) -o $(KERNEL_ELF) $(KERNEL_OBJ)

$(KERNEL_BIN): $(KERNEL_ELF)
	$(OBJC) -O binary $(KERNEL_ELF) $(KERNEL_BIN)