#CPU FEATURES
$(CPU_FEATURES_OBJ): $(CPU_FEATURES_CPP) $(CPU_FEATURES_H)
	$(CC) $(COMPILE_FLAGS) -c $(CPU_FEATURES_CPP) -o $(CPU_FEATURES_OBJ)

#CPU GDT
$(CPU_GDT_OBJ): $(CPU_GDT_CPP) $(CPU_GDT_CPP)
	$(CC) $(COMPILE_FLAGS) -c $(CPU_FEATURES_CPP) -o $(CPU_FEATURES_OBJ) 