$(BOOT_STAGE_2_OBJ): $(BOOT_STAGE_2)
	$(AS) $(BOOT_STAGE_2) -o $(BOOT_STAGE_2_OBJ)

$(BOOT_STAGE_2_ELF): $(BOOT_STAGE_2_OBJ)
	$(LD) -T $(BOOT_2_LINKER) -o $(BOOT_STAGE_2_ELF) $(BOOT_STAGE_2_OBJ)

$(BOOT_STAGE_2_BIN): $(BOOT_STAGE_2_ELF)
	$(OBJC) -O binary $(BOOT_STAGE_2_ELF) $(BOOT_STAGE_2_BIN)