# Keyboard
$(KEYBOARD_OBJ): $(KEYBOARD_CPP) $(KEYBOARD_H) $(IO_H) $(KEYBOARD_KEY_LIST_H) $(INTERRUPT_GUARD_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_ALL_FOLDERS) $(INCLUDE_DRIVERS_INTERNAL_FOLDER) -c $(KEYBOARD_CPP) -o $(KEYBOARD_OBJ)