# Shell Rules
$(SHELL_OBJ): $(SHELL_CPP) $(SHELL_H) $(SHELL_COMMAND_LIST) $(INPUT_H) $(KEYBOARD_H) $(KERNEL_CPU_INTERRUPTS_H)
	$(CC) $(COMPILE_FLAGS) -MD $(INCLUDE_KERNEL_FOLDER) $(INCLUDE_UTILITIES_FOLDER) $(INCLUDE_DRIVERS_FOLDER) -c $(SHELL_CPP) -o $(SHELL_OBJ)