# Terminal Output
$(OUTPUT_OBJ): $(VGA_H) $(TERMINAL_H) $(OUTPUT_CPP) $(IO_H) $(LOGGER_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) -c $(OUTPUT_CPP) -o $(OUTPUT_OBJ)

# Terminal Input
$(INPUT_OBJ): $(INPUT_CPP) $(INPUT_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) $(INCLUDE_DRIVERS_FOLDER) -c $(INPUT_CPP) -o $(INPUT_OBJ)

# VGA cursor
$(CURSOR_OBJ): $(IO_H) $(CURSOR_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) -c $(CURSOR_CPP) -o $(CURSOR_OBJ)

# VGA Buffer
$(VGA_OBJ): $(VGA_CPP) $(VGA_H)
	$(CC) $(COMPILE_FLAGS) $(INCLUDE_UTILITIES_FOLDER) -c $(VGA_CPP) -o $(VGA_OBJ)